const Graph = require('./graph')
const { findRoutePath } = require('./utils')

const pairCosts = new Graph()
pairCosts.addEdge('A', 'Z', 1)
pairCosts.addEdge('Z', 'X', 2)
pairCosts.addEdge('X', 'A', 1)
pairCosts.addEdge('A', 'B', 5)
pairCosts.addEdge('B', 'C', 4)
pairCosts.addEdge('C', 'D', 8)
pairCosts.addEdge('D', 'C', 8)
pairCosts.addEdge('D', 'E', 6)
pairCosts.addEdge('A', 'D', 5)
pairCosts.addEdge('C', 'E', 2)
pairCosts.addEdge('E', 'B', 3)
pairCosts.addEdge('A', 'E', 7)
pairCosts.addEdge('B', 'A', 4)

console.log(findRoutePath(pairCosts, 'A', 'A', true))
console.log(findRoutePath(pairCosts, 'A', 'A', false))
